/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Flower = IDL.Record({
  'color' : IDL.Text,
  'quantity' : IDL.Nat,
  'flowerType' : IDL.Text,
});
export const BouquetSecret = IDL.Record({
  'secretMessage' : IDL.Opt(IDL.Text),
  'secretImageUrl' : IDL.Opt(IDL.Text),
  'flowerType' : IDL.Text,
});
export const CoupleGif = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'name' : IDL.Text,
});
export const Bouquet = IDL.Record({
  'id' : IDL.Nat,
  'ribbonStyle' : IDL.Text,
  'cardMessage' : IDL.Opt(IDL.Text),
  'secret' : IDL.Opt(BouquetSecret),
  'creatorName' : IDL.Opt(IDL.Text),
  'wrappingStyle' : IDL.Text,
  'flowers' : IDL.Vec(Flower),
});
export const RoseDayWish = IDL.Record({
  'id' : IDL.Nat,
  'note' : IDL.Opt(IDL.Text),
  'bouquetId' : IDL.Opt(IDL.Nat),
  'message' : IDL.Text,
  'senderName' : IDL.Text,
  'recipientName' : IDL.Text,
  'gifUrl' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addCoupleGif' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createBouquet' : IDL.Func(
      [
        IDL.Vec(Flower),
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(BouquetSecret),
      ],
      [IDL.Nat],
      [],
    ),
  'createWish' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'editWish' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'filterCoupleGifsByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CoupleGif)],
      ['query'],
    ),
  'getAllBouquets' : IDL.Func([], [IDL.Vec(Bouquet)], ['query']),
  'getAllCoupleGifs' : IDL.Func([], [IDL.Vec(CoupleGif)], ['query']),
  'getAllWishes' : IDL.Func([], [IDL.Vec(RoseDayWish)], ['query']),
  'getBouquet' : IDL.Func([IDL.Nat], [Bouquet], ['query']),
  'getCoupleGif' : IDL.Func([IDL.Nat], [CoupleGif], ['query']),
  'getWish' : IDL.Func([IDL.Nat], [RoseDayWish], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Flower = IDL.Record({
    'color' : IDL.Text,
    'quantity' : IDL.Nat,
    'flowerType' : IDL.Text,
  });
  const BouquetSecret = IDL.Record({
    'secretMessage' : IDL.Opt(IDL.Text),
    'secretImageUrl' : IDL.Opt(IDL.Text),
    'flowerType' : IDL.Text,
  });
  const CoupleGif = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'name' : IDL.Text,
  });
  const Bouquet = IDL.Record({
    'id' : IDL.Nat,
    'ribbonStyle' : IDL.Text,
    'cardMessage' : IDL.Opt(IDL.Text),
    'secret' : IDL.Opt(BouquetSecret),
    'creatorName' : IDL.Opt(IDL.Text),
    'wrappingStyle' : IDL.Text,
    'flowers' : IDL.Vec(Flower),
  });
  const RoseDayWish = IDL.Record({
    'id' : IDL.Nat,
    'note' : IDL.Opt(IDL.Text),
    'bouquetId' : IDL.Opt(IDL.Nat),
    'message' : IDL.Text,
    'senderName' : IDL.Text,
    'recipientName' : IDL.Text,
    'gifUrl' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addCoupleGif' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createBouquet' : IDL.Func(
        [
          IDL.Vec(Flower),
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(BouquetSecret),
        ],
        [IDL.Nat],
        [],
      ),
    'createWish' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'editWish' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'filterCoupleGifsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CoupleGif)],
        ['query'],
      ),
    'getAllBouquets' : IDL.Func([], [IDL.Vec(Bouquet)], ['query']),
    'getAllCoupleGifs' : IDL.Func([], [IDL.Vec(CoupleGif)], ['query']),
    'getAllWishes' : IDL.Func([], [IDL.Vec(RoseDayWish)], ['query']),
    'getBouquet' : IDL.Func([IDL.Nat], [Bouquet], ['query']),
    'getCoupleGif' : IDL.Func([IDL.Nat], [CoupleGif], ['query']),
    'getWish' : IDL.Func([IDL.Nat], [RoseDayWish], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };