/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bouquet {
  'id' : bigint,
  'ribbonStyle' : string,
  'cardMessage' : [] | [string],
  'secret' : [] | [BouquetSecret],
  'creatorName' : [] | [string],
  'wrappingStyle' : string,
  'flowers' : Array<Flower>,
}
export interface BouquetSecret {
  'secretMessage' : [] | [string],
  'secretImageUrl' : [] | [string],
  'flowerType' : string,
}
export interface CoupleGif { 'id' : bigint, 'url' : string, 'name' : string }
export interface Flower {
  'color' : string,
  'quantity' : bigint,
  'flowerType' : string,
}
export interface RoseDayWish {
  'id' : bigint,
  'note' : [] | [string],
  'bouquetId' : [] | [bigint],
  'message' : string,
  'senderName' : string,
  'recipientName' : string,
  'gifUrl' : [] | [string],
}
export interface _SERVICE {
  'addCoupleGif' : ActorMethod<[string, string], bigint>,
  'createBouquet' : ActorMethod<
    [
      Array<Flower>,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [BouquetSecret],
    ],
    bigint
  >,
  'createWish' : ActorMethod<
    [string, string, string, [] | [bigint], [] | [string], [] | [string]],
    bigint
  >,
  'editWish' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      [] | [bigint],
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'filterCoupleGifsByName' : ActorMethod<[string], Array<CoupleGif>>,
  'getAllBouquets' : ActorMethod<[], Array<Bouquet>>,
  'getAllCoupleGifs' : ActorMethod<[], Array<CoupleGif>>,
  'getAllWishes' : ActorMethod<[], Array<RoseDayWish>>,
  'getBouquet' : ActorMethod<[bigint], Bouquet>,
  'getCoupleGif' : ActorMethod<[bigint], CoupleGif>,
  'getWish' : ActorMethod<[bigint], RoseDayWish>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];