/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Bouquet {
    id: bigint;
    ribbonStyle: string;
    cardMessage?: string;
    secret?: BouquetSecret;
    creatorName?: string;
    wrappingStyle: string;
    flowers: Array<Flower>;
}
export interface CoupleGif {
    id: bigint;
    url: string;
    name: string;
}
export interface Flower {
    color: string;
    quantity: bigint;
    flowerType: string;
}
export interface RoseDayWish {
    id: bigint;
    note?: string;
    bouquetId?: bigint;
    message: string;
    senderName: string;
    recipientName: string;
    gifUrl?: string;
}
export interface BouquetSecret {
    secretMessage?: string;
    secretImageUrl?: string;
    flowerType: string;
}
export interface backendInterface {
    addCoupleGif(name: string, url: string): Promise<bigint>;
    createBouquet(flowers: Array<Flower>, wrappingStyle: string, ribbonStyle: string, cardMessage: string | null, creatorName: string | null, secret: BouquetSecret | null): Promise<bigint>;
    createWish(senderName: string, recipientName: string, message: string, bouquetId: bigint | null, note: string | null, gifUrl: string | null): Promise<bigint>;
    editWish(id: bigint, senderName: string, recipientName: string, message: string, bouquetId: bigint | null, note: string | null, gifUrl: string | null): Promise<void>;
    filterCoupleGifsByName(substring: string): Promise<Array<CoupleGif>>;
    getAllBouquets(): Promise<Array<Bouquet>>;
    getAllCoupleGifs(): Promise<Array<CoupleGif>>;
    getAllWishes(): Promise<Array<RoseDayWish>>;
    getBouquet(id: bigint): Promise<Bouquet>;
    getCoupleGif(id: bigint): Promise<CoupleGif>;
    getWish(id: bigint): Promise<RoseDayWish>;
}
import type { Bouquet as _Bouquet, BouquetSecret as _BouquetSecret, Flower as _Flower, RoseDayWish as _RoseDayWish } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCoupleGif(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCoupleGif(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCoupleGif(arg0, arg1);
            return result;
        }
    }
    async createBouquet(arg0: Array<Flower>, arg1: string, arg2: string, arg3: string | null, arg4: string | null, arg5: BouquetSecret | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBouquet(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBouquet(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async createWish(arg0: string, arg1: string, arg2: string, arg3: bigint | null, arg4: string | null, arg5: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createWish(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWish(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async editWish(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint | null, arg5: string | null, arg6: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editWish(arg0, arg1, arg2, arg3, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editWish(arg0, arg1, arg2, arg3, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async filterCoupleGifsByName(arg0: string): Promise<Array<CoupleGif>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterCoupleGifsByName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterCoupleGifsByName(arg0);
            return result;
        }
    }
    async getAllBouquets(): Promise<Array<Bouquet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBouquets();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBouquets();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCoupleGifs(): Promise<Array<CoupleGif>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCoupleGifs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCoupleGifs();
            return result;
        }
    }
    async getAllWishes(): Promise<Array<RoseDayWish>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWishes();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWishes();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBouquet(arg0: bigint): Promise<Bouquet> {
        if (this.processError) {
            try {
                const result = await this.actor.getBouquet(arg0);
                return from_candid_Bouquet_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBouquet(arg0);
            return from_candid_Bouquet_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoupleGif(arg0: bigint): Promise<CoupleGif> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoupleGif(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoupleGif(arg0);
            return result;
        }
    }
    async getWish(arg0: bigint): Promise<RoseDayWish> {
        if (this.processError) {
            try {
                const result = await this.actor.getWish(arg0);
                return from_candid_RoseDayWish_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWish(arg0);
            return from_candid_RoseDayWish_n14(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BouquetSecret_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BouquetSecret): BouquetSecret {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Bouquet_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bouquet): Bouquet {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_RoseDayWish_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoseDayWish): RoseDayWish {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BouquetSecret]): BouquetSecret | null {
    return value.length === 0 ? null : from_candid_BouquetSecret_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    secretMessage: [] | [string];
    secretImageUrl: [] | [string];
    flowerType: string;
}): {
    secretMessage?: string;
    secretImageUrl?: string;
    flowerType: string;
} {
    return {
        secretMessage: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.secretMessage)),
        secretImageUrl: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.secretImageUrl)),
        flowerType: value.flowerType
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    note: [] | [string];
    bouquetId: [] | [bigint];
    message: string;
    senderName: string;
    recipientName: string;
    gifUrl: [] | [string];
}): {
    id: bigint;
    note?: string;
    bouquetId?: bigint;
    message: string;
    senderName: string;
    recipientName: string;
    gifUrl?: string;
} {
    return {
        id: value.id,
        note: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.note)),
        bouquetId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.bouquetId)),
        message: value.message,
        senderName: value.senderName,
        recipientName: value.recipientName,
        gifUrl: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.gifUrl))
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    ribbonStyle: string;
    cardMessage: [] | [string];
    secret: [] | [_BouquetSecret];
    creatorName: [] | [string];
    wrappingStyle: string;
    flowers: Array<_Flower>;
}): {
    id: bigint;
    ribbonStyle: string;
    cardMessage?: string;
    secret?: BouquetSecret;
    creatorName?: string;
    wrappingStyle: string;
    flowers: Array<Flower>;
} {
    return {
        id: value.id,
        ribbonStyle: value.ribbonStyle,
        cardMessage: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.cardMessage)),
        secret: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.secret)),
        creatorName: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.creatorName)),
        wrappingStyle: value.wrappingStyle,
        flowers: value.flowers
    };
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RoseDayWish>): Array<RoseDayWish> {
    return value.map((x)=>from_candid_RoseDayWish_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bouquet>): Array<Bouquet> {
    return value.map((x)=>from_candid_Bouquet_n7(_uploadFile, _downloadFile, x));
}
function to_candid_BouquetSecret_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BouquetSecret): _BouquetSecret {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BouquetSecret | null): [] | [_BouquetSecret] {
    return value === null ? candid_none() : candid_some(to_candid_BouquetSecret_n3(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    secretMessage?: string;
    secretImageUrl?: string;
    flowerType: string;
}): {
    secretMessage: [] | [string];
    secretImageUrl: [] | [string];
    flowerType: string;
} {
    return {
        secretMessage: value.secretMessage ? candid_some(value.secretMessage) : candid_none(),
        secretImageUrl: value.secretImageUrl ? candid_some(value.secretImageUrl) : candid_none(),
        flowerType: value.flowerType
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
